config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
  root to: "static_pages#home"
  devise_for :users, path: "account",
    controllers: {sessions: "sessions", registrations: "users"}
  devise_scope :user do
    match "/users/:id", to: "users#show", via: "get"
  end
  resources :users
  resources :reports do
    get "page/:page", action: :index, on: :collection
  end
  resources :courses do
    resources :subjects, only: %i(show update) do
      resources :user_subjects
    end
  end
  namespace :supervisor do
    resources :members
    resources :users
    resources :courses do
      resources :subjects
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_course, only: %i(show update)
  before_action :check_start, :check_close, only: :show

  def index
    @q = current_user.courses.not_closed.sort_by_date.ransack params[:q]
    @courses = @q.result.page(params[:page]).per Settings.per_page
    @total = current_user.courses.not_closed.count
    @locked = current_user.count_courses_locked
    @inprogress = current_user.count_courses_inprogress
    @completed = current_user.count_courses_completed
  end

  def show
    @q = @course.subjects.sort_by_date.ransack params[:q]
    @subjects = @q.result.page(params[:page]).per Settings.per_page
  end

  def update
    if params[:commit]
      @course.subjects.each do |subject|
        @course.user_subjects.build(subject_id: subject.id, user_id: current_user.id)
      end
      if @course.save
        flash[:success] = t ".create_success"
        redirect_to @course
      else
        flash[:danger] = t ".create_fail"
        redirect_back fallback_location: root_url
      end
    end
  end

  private

  def load_course
    @course = Course.find_by slug: params[:id]
    return if @course
    flash[:danger] = t ".course_not_exist"
    redirect_back fallback_location: root_url
  end

  def check_start
    return if current_user.courses_started.include? @course
    flash[:danger] = t ".course_not_started"
    redirect_back fallback_location: root_url
  end

  def check_close
    return unless @course.closed?
    flash[:danger] = t ".course_closed"
    redirect_back fallback_location: root_url
  end
end

app/controllers/supervisor/courses_controller.rb
class Supervisor::CoursesController < Supervisor::SupervisorBaseController
  before_action :load_course, except: %i(index new create)

  def index
    @q = Course.lastest.ransack params[:q]
    @courses = @q.result.fields.page(params[:page]).per Settings.per_page
  end

  def new
    @course = Course.new
  end

  def show
    @subjects = @course.subjects
    @trainees_in_course = @course.users.trainee.
      page(params[:trainees_in]).per Settings.per_page
    @trainees_not_in_course = User.trainee.not_in_course(@course).
      page(params[:trainees_not_in]).per Settings.per_page
    @supervisors_in_course = @course.users.supervisor.
      page(params[:supervisors_in]).per Settings.per_page
    @supervisors_not_in_course = User.supervisor.not_in_course(@course).
      page(params[:supervisors_not_in]).per Settings.per_page
    @member = Member.new
  end

  def edit; end

  def create
    @course = Course.new course_params
    if @course.save
      flash[:success] = t ".create_success"
    else
      flash[:danger] = t ".create_fail"
    end
    redirect_back fallback_location: root_url
  end

  def update
    @course.update_attributes course_params
    if @course.save
      flash[:success] = t ".update_success"
    else
      flash[:danger] = t ".update_fail"
    end
    redirect_back fallback_location: root_url
  end

  def destroy
    if @course.destroy
      flash[:success] = t ".destroy_success"
    else
      flash[:danger] = t ".destroy_fail"
    end
    redirect_back fallback_location: root_url
  end

  private

  def course_params
    p = params.require(:course).permit :name, :description,
      :start_date, :end_date, :status, subjects_attributes:
      [:id, :name, :description, :detail, :start_date, :end_date, :_destroy,
      tasks_attributes: [:id, :detail, :_destroy]]
    p[:status] = params[:course][:status].to_i
    p
  end

  def load_course
    @course = Course.find_by slug: params[:id]
    return if @course
    flash[:danger] = t ".course_not_exist"
    redirect_back fallback_location: root_url
  end
end

app/controllers/supervisor/members_controller.rb
class Supervisor::MembersController < Supervisor::SupervisorBaseController
  include PublicActivity::StoreController
  before_action :load_member, only: :destroy
  before_action :load_user_and_course

  def create
    old = Member.only_deleted.find_by course_id: params[:member][:course_id],
      user_id: params[:member][:user_id]
    if old
      old.restore
      MyWorker.perform_async @user.email, @course.name, true
    else
      @member = Member.create member_params
      if @member.save
        MyWorker.perform_async @user.email, @course.name, true
        flash[:success] = t ".create_success"
      else
        flash[:danger] = t ".create_fail"
      end
    end
    redirect_back fallback_location: root_url
  end

  def destroy
    if @member.destroy
      MyWorker.perform_async @user.email, @course.name, false
      flash[:success] = t ".deleted_success"
    else
      flash[:danger] = t ".deleted_fail"
    end
    redirect_back fallback_location: root_url
  end

  private

  def member_params
    params.require(:member).permit :user_id, :course_id
  end

  def load_member
    @member = Member.find_by id: params[:id]
    return if @member
    flash[:danger] = t ".not_found"
    redirect_back fallback_location: root_url
  end

  def load_user_and_course
    if params[:member]
      @user = User.find_by id: params[:member][:user_id]
      @course = Course.find_by id: params[:member][:course_id]
    else
      @user = User.find_by id: params[:user_id]
      @course = Course.find_by id: params[:course_id]
    end
    return if @user && @course
    flash[:danger] = t ".user_not_found"
    redirect_back fallback_location: root_url
  end
end

app/controllers/supervisor/static_pages_controller.rb
module Supervisor
  class StaticPagesController < SupervisorBaseController
    def home; end
  end
end

app/controllers/supervisor/subjects_controller.rb
class Supervisor::SubjectsController < Supervisor::SupervisorBaseController
  before_action :load_subject

  def update
    @subject.update_attributes subject_params
    if @subject.save
      flash[:success] = t ".update_success"
    else
      flash[:danger] = t ".update_fail"
    end
    redirect_back fallback_location: root_url
  end

  private

  def subject_params
    p = params.require(:subject).permit :name, :description,
      :detail, :start_date, :end_date, :status
    p[:status] = params[:subject][:status].to_i
    p
  end

  def load_subject
    @course = Course.find_by slug: params[:course_id]
    return if @course
    flash[:danger] = t ".course_not_exist"
    redirect_back fallback_location: root_url
  end
end

app/controllers/supervisor/supervisor_base_controller.rb
class Supervisor::SupervisorBaseController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
end

app/controllers/supervisor/users_controller.rb
class Supervisor::UsersController < Supervisor::SupervisorBaseController
  def index
    @q = User.ransack params[:q]
    @users = @q.result.page(params[:page]).per Settings.per_page
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def course_start course
    current_user.courses_started.include? course
  end

  def course_done course
    current_user.user_subjects.where(course_id: course.id).find_by_status(true).count ==
      course.subjects.count
  end

  def count_user_subject course
    current_user.user_subjects.find_by_course(course).count
  end
end

app/views/supervisor/courses/_course.html.erb
<tr>
  <td>
  </td>
  <td>
    <%= link_to course.name, supervisor_course_path(course), class: "text-dark" %>
  </td>
  <td>
    <%= course.start_date %>
  </td>
  <td>
    <%= course.end_date %>
  </td>
  <td>
    <% if course.locked? %>
      <%= form_for course, url: supervisor_course_path(course) do |f| %>
        <%= f.hidden_field :status, value: Course.statuses[:opening] %>
        <%= f.submit t(".start"), class: "btn btn-success btn-sm" %>
      <% end %>
    <% elsif course.closed? %>
      <p class="text-danger"><%= t ".finished" %></p>
    <% else %>
      <%= form_for course, url: supervisor_course_path(course) do |f| %>
        <%= f.hidden_field :status, value: Course.statuses[:closed] %>
        <%= f.fields_for :subjects do |ff| %>
         <% subject = ff.object %>
         <% ff.hidden_field :status, value: Subject.statuses[:closed] %>
        <% end %>
        <%= f.submit t(".finish"), class: "btn btn-danger btn-sm" %>
      <% end %>
    <% end %>
  </td>
  <td>
    <%= link_to edit_supervisor_course_path(course),
      class: "btn btn-primary btn-link btn-sm",rel: "tooltip", title: t(".edit") do %>
       <i class="material-icons">edit</i>
    <% end %>
    <%= link_to supervisor_course_path(course), method: :delete,
      data: {confirm: t(".confirm")}, class: "btn btn-danger btn-link btn-sm",rel: "tooltip",title: t(".delete") do %>
       <i class="material-icons">close</i>
    <% end %>
  </td>
</tr>

app/views/supervisor/courses/_subject_field.html.erb
<div class="col-md-6 field">
  <div class="card">
    <div class="card-header card-header-success">
      <h4 class="card-title"><%= t ".create_subject" %></h4>
      <p class="card-category"><%= t ".create_subject_msg" %></p>
    </div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <%= f.label :name, class: "bmd-label-floating" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
            <%= f.label :start_date %>
            <%= f.date_field :start_date, class: "form-control" %>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
            <%= f.label :end_date %>
            <%= f.date_field :end_date, class: "form-control" %>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6">
          <div class="form-group">
            <div class="form-group">
              <%= f.label :description, class: "bmd-label-floating" %>
              <%= f.text_area :description, class: "form-control", rows: Settings.row %>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="form-group">
            <div class="form-group">
              <%= f.label :detail, class: "bmd-label-floating" %>
              <%= f.text_area :detail, class: "form-control", rows: Settings.row %>
            </div>
          </div>
        </div>
        <%= f.fields_for :tasks do |ff| %>
          <%= render "task_field", f: ff %>
        <% end %>
        <%= f.hidden_field :status, value: Subject.statuses[f.object.status] %>
        <%= f.hidden_field :_destroy %>
        <%= link_to "remove", '#',
          class: "remove_fields btn btn-danger btn-sm pull-right" %>
        <%= link_to_add_fields t(".add_task"), f, :tasks %>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>

app/views/supervisor/courses/_task_field.html.erb
<div class="col-md-12 field">
  <div class="form-group">
    <div class="form-group">
      <%= f.label :detail, "Task detail", class: "bmd-label-floating"%>
      <%= f.text_area :detail, class: "form-control" %>
      <%= f.hidden_field :_destroy %>
      <button type="button" rel="tooltip"
        class="remove_fields btn btn-danger btn-link btn-sm pull-right">
        <i class="material-icons">close</i>
      </button>
    </div>
  </div>
</div>

app/views/supervisor/courses/_user_course.html.erb
<tr>
  <td>
    <%= user.email %>
  </td>
  <td>
    <%= link_to supervisor_member_path(user), method: :delete,
      data: {confirm: t(".confirm")}, class: "btn btn-danger btn-link btn-sm",
      rel: "tooltip", title: t(".delete") do %>
       <i class="material-icons">close</i>
    <% end %>
  </td>
</tr>

app/views/supervisor/courses/_user_in_course.html.erb
<tr>
  <td></td>
  <td>
    <%= user.name %>
  </td>
  <td class="w-25">
    <%= link_to t(".remove"), supervisor_member_path(find_member(user, @course),
      user_id: user.id, course_id: @course.id),
      method: :delete, data: {confirm: t(".confirm")}, class: "btn btn-danger btn-danger btn-sm" %>
  </td>
</tr>

app/views/supervisor/courses/_user_not_in_course.html.erb
<tr>
  <td></td>
  <td>
    <%= user.name %>
  </td>
  <td class="w-25">
    <%= form_for @member, url: supervisor_members_path do |f| %>
    <%= f.hidden_field :user_id, value: user.id %>
    <%= f.hidden_field :course_id, value: @course.id %>
    <%= f.submit t(".add"), class: "btn btn-success btn-sm" %>
    <% end %>
  </td>
</tr>

app/views/supervisor/courses/edit.html.erb
<div class="content">
  <%= form_for @course, url: supervisor_course_path do |f| %>
    <%= f.hidden_field :status, value: Course.statuses[@course.status] %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header card-header-primary">
              <h4 class="card-title"><%= t ".create_course" %></h4>
              <p class="card-category"><%= t ".create_course_msg" %></p>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.label :start_date %>
                    <%= f.date_field :start_date, class: "form-control" %>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.label :end_date %>
                    <%= f.date_field :end_date, class: "form-control" %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <%= f.label :name, class: "bmd-label-floating" %>
                    <%= f.text_field :name, class: "form-control" %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <div class="form-group">
                      <%= f.label :description, class: "bmd-label-floating" %>
                      <%= f.text_area :description, class: "form-control", rows: Settings.row %>
                    </div>
                  </div>
                </div>
              </div>
              <%= f.submit t(".submit"),
                class: "btn btn-primary pull-right" %>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
        <%= f.fields_for :subjects do |ff| %>
          <%= render "subject_field", f: ff %>
        <% end %>
        <%= link_to_add_fields t(".add_subject"), f, :subjects %>
      </div>
    </div>
  <% end %>
</div>

app/views/supervisor/courses/index.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <%= search_form_for @q, url: supervisor_courses_path,
          class: "navbar-form w-50" do |f| %>
          <div class="input-group no-border">
            <%= f.search_field :name_cont, class: "form-control",
              placeholder: t(".search") %>
            <%= f.submit class:"btn btn-primary btn-sm" %>
          </div>
        <% end %>
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title "><%= t ".courses" %></h4>
            <p class="card-category">
              <%= t(".courses_total", count: Course.count) %>
            </p>
          </div>
          <div class="card-body">
            <%= link_to t(".add_course"), new_supervisor_course_path,
              class: "btn btn-primary pull-right" %>
            <%= t(".results_found", count: @q.result.count) %>
            <div class="table-responsive">
              <table class="table">
                <thead class=" text-primary">
                  <th>
                    #
                  </th>
                  <th>
                    <%= sort_link(@q, :name) do %>
                      <%= t ".course_name" %>
                    <% end %>
                  </th>
                  <th>
                    <%= sort_link(@q, :start_date) do %>
                      <%= t ".course_sd" %>
                    <% end %>
                  </th>
                  <th>
                    <%= sort_link(@q, :end_date) do %>
                      <%= t ".course_ed" %>
                    <% end %>
                  </th>
                  <th>
                    <%= t ".course_stt" %>
                  </th>
                  <th>
                    #
                  </th>
                </thead>
                <tbody>
                  <%= render @courses %>
                </tbody>
              </table>
              <%= paginate @courses %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/supervisor/courses/new.html.erb
<div class="content">
  <%= form_for @course, url: supervisor_courses_path do |f| %>
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12">
          <div class="card">
            <div class="card-header card-header-primary">
              <h4 class="card-title"><%= t ".create_course" %></h4>
              <p class="card-category"><%= t ".create_course_msg" %></p>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.label :start_date %>
                    <%= f.date_field :start_date, class: "form-control" %>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.label :end_date %>
                    <%= f.date_field :end_date, class: "form-control" %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <%= f.label :name, class: "bmd-label-floating" %>
                    <%= f.text_field :name, class: "form-control" %>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <div class="form-group">
                      <%= f.label :description, class: "bmd-label-floating" %>
                      <%= f.text_area :description, class: "form-control", rows: Settings.row %>
                    </div>
                  </div>
                </div>
              </div>
              <%= f.submit t(".submit"),
                class: "btn btn-primary pull-right" %>
              <div class="clearfix"></div>
            </div>
          </div>
        </div>
        <%= link_to_add_fields t(".add_subject"), f, :subjects %>
      </div>
    </div>
  <% end %>
</div>

app/views/supervisor/courses/show.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title "><%= t ".subject" %><%= @course.name %></h4>
            <p class="card-category"><%= t ".subject_msg" %></p>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead class="text-primary">
                  <th>#</th>
                  <th>
                    <%= t ".subject_name" %>
                  </th>
                  <th>
                    <%= t ".subject_sd" %>
                  </th>
                  <th>
                    <%= t ".subject_ed" %>
                  </th>
                  <th>
                    <%= t ".subject_stt" %>
                  </th>
                </thead>
                <tbody>
                  <%= render @subjects %>
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card">
          <div class="card-header card-header-warning">
            <h4 class="card-title ">
              <%= t(".trainees_in_course", count: @course.users.trainee.count) %>
            </h4>
            <p class="card-category"><%= t ".trainees_in_course_msg" %></p>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead class="text-primary">
                  <th>#</th>
                  <th>
                    <%= t ".trainee" %>
                  </th>
                  <th>
                    #
                  </th>
                </thead>
                <tbody id="trainees_in">
                  <%= render partial: "user_in_course",
                    collection: @trainees_in_course, as: :user %>
                </tbody>
              </table>
              <div id="paginator_trainees_in">
                <%= paginate @trainees_in_course,
                  remote: true %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card">
          <div class="card-header card-header-warning">
            <h4 class="card-title ">
              <%= t(".trainees_not_in_course",
                count: User.trainee.not_in_course(@course).count) %>
              </h4>
            <p class="card-category"><%= t ".trainees_not_in_course_msg" %></p>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead class="text-primary">
                  <th>#</th>
                  <th>
                    <%= t ".trainee" %>
                  </th>
                  <th>
                    #
                  </th>
                </thead>
                <tbody id="trainees_not_in">
                  <%= render partial: "user_not_in_course",
                    collection: @trainees_not_in_course, as: :user %>
                </tbody>
              </table>
              <div id="paginator_trainees_not_in">
                <%= paginate @trainees_not_in_course,
                  param_name: "trainees_not_in", remote: true %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card">
          <div class="card-header card-header-danger">
            <h4 class="card-title ">
              <%= t(".supervisors_in_course",
                count: @course.users.supervisor.count)  %>
            </h4>
            <p class="card-category"><%= t ".supervisors_in_course_msg" %></p>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead class="text-primary">
                  <th>#</th>
                  <th>
                    <%= t ".supervisor" %>
                  </th>
                  <th>
                    #
                  </th>
                </thead>
                <tbody id="supervisors_in">
                  <%= render partial: "user_in_course",
                    collection: @supervisors_in_course, as: :user %>
                </tbody>
              </table>
              <div id="paginator_supervisors_in">
                <%= paginate @supervisors_in_course, param_name: "supervisors_in",
                  remote: true %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="card">
          <div class="card-header card-header-danger">
            <h4 class="card-title ">
              <%= t(".supervisors_not_in_course",
                count: User.supervisor.not_in_course(@course).count) %>
            </h4>
            <p class="card-category"><%= t ".supervisors_not_in_course_msg" %></p>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table">
                <thead class="text-primary">
                  <th>#</th>
                  <th>
                    <%= t ".supervisor" %>
                  </th>
                  <th>
                    #
                  </th>
                </thead>
                <tbody id="supervisors_not_in">
                  <%= render partial: "user_not_in_course",
                    collection: @supervisors_not_in_course,
                      as: :user %>
                </tbody>
              </table>
              <div id="paginator_supervisors_not_in">
                <%= paginate @supervisors_not_in_course, param_name: "supervisors_not_in", remote: true %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/supervisor/courses/show.js.erb
$('#trainees_in').html("<%= j render partial: 'user_in_course', collection: @trainees_in_course, as: :user %>");
$('#paginator_trainees_in').html("<%= j paginate(@trainees_in_course, param_name: 'trainees_in', remote: true) %>");
$('#trainees_not_in').html("<%= j render partial: 'user_not_in_course', collection: @trainees_not_in_course, as: :user %>");
$('#paginator_trainees_not_in').html("<%= j paginate(@trainees_not_in_course, param_name: 'trainees_not_in', remote: true) %>");
$('#supervisors_in').html("<%= j render partial: "user_in_course", collection: @supervisors_in_course, as: :user %>");
$('#paginator_supervisors_in').html("<%= j paginate(@supervisors_in_course, param_name: 'supervisors_in', remote: true) %>");
$('#supervisors_not_in').html("<%= j render partial: "user_not_in_course", collection: @supervisors_not_in_course, as: :user %>");
$('#paginator_supervisors_not_in').html("<%= j paginate(@supervisors_not_in_course, param_name: 'supervisors_not_in', remote: true) %>");