config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
  root to: "static_pages#home"
  devise_for :users, path: "account",
    controllers: {sessions: "sessions", registrations: "users"}
  devise_scope :user do
    match "/users/:id", to: "users#show", via: "get"
  end
  resources :users
  resources :reports do
    get "page/:page", action: :index, on: :collection
  end
  resources :courses do
    resources :subjects, only: %i(show update) do
      resources :user_subjects
    end
  end
  namespace :supervisor do
    resources :members
    resources :users
    resources :courses do
      resources :subjects
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :load_course, only: %i(show update)
  before_action :check_start, :check_close, only: :show

  def index
    @q = current_user.courses.not_closed.sort_by_date.ransack params[:q]
    @courses = @q.result.page(params[:page]).per Settings.per_page
    @total = current_user.courses.not_closed.count
    @locked = current_user.count_courses_locked
    @inprogress = current_user.count_courses_inprogress
    @completed = current_user.count_courses_completed
  end

  def show
    @q = @course.subjects.sort_by_date.ransack params[:q]
    @subjects = @q.result.page(params[:page]).per Settings.per_page
  end

  def update
    if params[:commit]
      @course.subjects.each do |subject|
        @course.user_subjects.build(subject_id: subject.id, user_id: current_user.id)
      end
      if @course.save
        flash[:success] = t ".create_success"
        redirect_to @course
      else
        flash[:danger] = t ".create_fail"
        redirect_back fallback_location: root_url
      end
    end
  end

  private

  def load_course
    @course = Course.find_by slug: params[:id]
    return if @course
    flash[:danger] = t ".course_not_exist"
    redirect_back fallback_location: root_url
  end

  def check_start
    return if current_user.courses_started.include? @course
    flash[:danger] = t ".course_not_started"
    redirect_back fallback_location: root_url
  end

  def check_close
    return unless @course.closed?
    flash[:danger] = t ".course_closed"
    redirect_back fallback_location: root_url
  end
end

app/controllers/supervisor/courses_controller.rb
class Supervisor::CoursesController < Supervisor::SupervisorBaseController
  before_action :load_course, except: %i(index new create)

  def index
    @q = Course.lastest.ransack params[:q]
    @courses = @q.result.fields.page(params[:page]).per Settings.per_page
  end

  def new
    @course = Course.new
  end

  def show
    @subjects = @course.subjects
    @trainees_in_course = @course.users.trainee.
      page(params[:trainees_in]).per Settings.per_page
    @trainees_not_in_course = User.trainee.not_in_course(@course).
      page(params[:trainees_not_in]).per Settings.per_page
    @supervisors_in_course = @course.users.supervisor.
      page(params[:supervisors_in]).per Settings.per_page
    @supervisors_not_in_course = User.supervisor.not_in_course(@course).
      page(params[:supervisors_not_in]).per Settings.per_page
    @member = Member.new
  end

  def edit; end

  def create
    @course = Course.new course_params
    if @course.save
      flash[:success] = t ".create_success"
    else
      flash[:danger] = t ".create_fail"
    end
    redirect_back fallback_location: root_url
  end

  def update
    @course.update_attributes course_params
    if @course.save
      flash[:success] = t ".update_success"
    else
      flash[:danger] = t ".update_fail"
    end
    redirect_back fallback_location: root_url
  end

  def destroy
    if @course.destroy
      flash[:success] = t ".destroy_success"
    else
      flash[:danger] = t ".destroy_fail"
    end
    redirect_back fallback_location: root_url
  end

  private

  def course_params
    p = params.require(:course).permit :name, :description,
      :start_date, :end_date, :status, subjects_attributes:
      [:id, :name, :description, :detail, :start_date, :end_date, :_destroy,
      tasks_attributes: [:id, :detail, :_destroy]]
    p[:status] = params[:course][:status].to_i
    p
  end

  def load_course
    @course = Course.find_by slug: params[:id]
    return if @course
    flash[:danger] = t ".course_not_exist"
    redirect_back fallback_location: root_url
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
  def course_start course
    current_user.courses_started.include? course
  end

  def course_done course
    current_user.user_subjects.where(course_id: course.id).find_by_status(true).count ==
      course.subjects.count
  end

  def count_user_subject course
    current_user.user_subjects.find_by_course(course).count
  end
end

app/views/courses/_course.html.erb
<tr>
  <td>
  </td>
  <td>
    <%= link_to course.name, course_path(course), class: "text-dark" %>
  </td>
  <td>
    <%= course.start_date %>
  </td>
  <td>
    <%= course.end_date %>
  </td>
  <td>
    <% if course.locked? %>
      <i class="material-icons text-danger">lock</i>
    <% else %>
      <% if course_start course %>
        <% if course_done course %>
          <i class="material-icons text-success">done</i>
        <% else %>
          <i class="material-icons text-warning">cached</i>
        <% end %>
      <% else %>
        <%= form_for course do |f| %>
          <%= f.submit t(".start"), class: "btn btn-primary btn-sm" %>
        <% end %>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/courses/_trainees_in_course.html.erb
<tr>
  <td>
  </td>
  <td>
    <%= link_to user.name, user, class: "text-dark" %>
  </td>
</tr>

app/views/courses/index.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-primary card-header-icon">
            <div class="card-icon">
              <i class="material-icons"><%= Settings.icons_search %></i>
            </div>
            <p class="card-category"><%= t ".total_courses" %></p>
            <h3 class="card-title"><%= @total %></h3>
          </div>
          <div class="card-footer">
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-warning card-header-icon">
            <div class="card-icon">
              <i class="material-icons"><%= Settings.icons_cached %></i>
            </div>
            <p class="card-category"><%= t ".inprogress" %></p>
            <h3 class="card-title"><%= @inprogress %></h3>
          </div>
          <div class="card-footer">
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-success card-header-icon">
            <div class="card-icon">
              <i class="material-icons"><%= Settings.icons_done %></i>
            </div>
            <p class="card-category"><%= t ".completed" %></p>
            <h3 class="card-title"> <%= @completed %></h3>
          </div>
          <div class="card-footer">
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-md-6 col-sm-6">
        <div class="card card-stats">
          <div class="card-header card-header-danger card-header-icon">
            <div class="card-icon">
              <i class="material-icons"><%= Settings.icons_https %></i>
            </div>
            <p class="card-category"><%= t ".not_started_or_closed" %></p>
            <h3 class="card-title"><%= @locked %></h3>
          </div>
          <div class="card-footer">
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= search_form_for @q, url: courses_path,
          class: "navbar-form w-50" do |f| %>
          <div class="input-group no-border">
            <%= f.search_field :name_cont, class: "form-control",
              placeholder: t(".search") %>
            <%= f.submit class:"btn btn-primary btn-sm" %>
          </div>
        <% end %>
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title "><%= t ".your_courses" %></h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <%= t(".results_found", count: @q.result.count) %>
              <table class="table table-hover">
                <thead class=" text-primary">
                  <th>
                    #
                  </th>
                  <th>
                    <%= sort_link(@q, :name) do %>
                      <%= t ".name" %>
                    <% end %>
                  </th>
                  <th>
                    <%= sort_link(@q, :start_date) do %>
                      <%= t ".start" %>
                    <% end %>
                  </th>
                  <th>
                    <%= sort_link(@q, :end_date) do %>
                      <%= t ".end" %>
                    <% end %>
                  </th>
                  <th>
                    <%= t ".status" %>
                  </th>
                </thead>
                <tbody>
                  <%= render @courses %>
                </tbody>
              </table>
              <%= paginate @courses %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/courses/show.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header card-header-info">
            <h4 class="card-title ">
              <%= @course.name %>
            </h4>
            <p class="card-category">
            </p>
          </div>
          <div class="card-body">
            <p>
              <%= @course.description %>
            </p>
          </div>
        </div>
      </div>
      <div class="col-md-12">
        <%= search_form_for @q, url: course_path(@course),
          class: "navbar-form w-50" do |f| %>
          <div class="input-group no-border">
            <%= f.search_field :name_cont, class: "form-control",
              placeholder: t(".search") %>
            <%= f.submit class:"btn btn-primary btn-sm" %>
          </div>
        <% end %>
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title "><%= t(".subject",
              count: @course.subjects.count) %></h4>
            <p class="card-category"><%= t ".subject_msg" %></p>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <%= paginate @subjects %>
              <%= t(".results_found", count: @q.result.count) %>
              <table class="table table-hover">
                <thead class=" text-primary">
                <th>
                  #
                </th>
                <th>
                  <%= sort_link(@q, :name) do %>
                    <%= t ".subject_name" %>
                  <% end %>
                </th>
                <th>
                  <%= sort_link(@q, :start_date) do %>
                    <%= t ".subject_sd" %>
                  <% end %>
                </th>
                <th>
                  <%= sort_link(@q, :end_date) do %>
                    <%= t ".subject_ed" %>
                  <% end %>
                </th>
                <th>
                  <%= t ".subject_stt" %>
                </th>
                </thead>
                <tbody>
                  <%= render @subjects %>
                </tbody>
              </table>
              <%= paginate @subjects %>
            </div>
          </div>
        </div>
        <%= link_to t(".back"), courses_path, class: "btn btn-primary btn-sm pull-right" %>
      </div>
      <div class="col-md-4">
        <div class="card">
          <div class="card-body">
            <div class="table-responsive">
              <%= t(".total_trainees",
               count: @course.users.trainee.count) %>
              <table class="table table-hover">
                <thead class="text-primary">
                <th>
                  #
                </th>
                <th>
                  <%= sort_link(@q, :name) do %>
                    <%= t ".trainee_name" %>
                  <% end %>
                </th>
                </thead>
                <tbody>
                  <%= render partial: "trainees_in_course", collection: @trainees,
                    as: :user %>
                </tbody>
              </table>
              <%= paginate @trainees %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-8">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title ">Activity</h4>
          </div>
          <div class="card-body">
            <ul>
              <%= render_activities @activities %>
            </ul>
            <%= paginate @activities %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>