config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"
  mount Sidekiq::Web => "/sidekiq"
  root to: "static_pages#home"
  devise_for :users, path: "account",
    controllers: {sessions: "sessions", registrations: "users"}
  devise_scope :user do
    match "/users/:id", to: "users#show", via: "get"
  end
  resources :users
  resources :reports do
    get "page/:page", action: :index, on: :collection
  end
  resources :courses do
    resources :subjects, only: %i(show update) do
      resources :user_subjects
    end
  end
  namespace :supervisor do
    resources :members
    resources :users
    resources :courses do
      resources :subjects
    end
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  validates :title, :content, presence: true
  scope :sort_by_date, ->{order updated_at: :desc}
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :authenticate_user!
  before_action :load_report, :correct_user, except: %i(new create index)

  def index
    @q = current_user.reports.sort_by_date.ransack params[:q]
    @reports = @q.result.page(params[:page]).per params[:limit]
    @report = Report.new
  end

  def create
    @report = current_user.reports.build report_params
    if @report.save
      flash[:success] = t ".create_success"
      redirect_to reports_url
    else
      flash[:danger] = t ".create_fail"
      render :new
    end
  end

  def edit; end

  def update
    if @report.update_attributes report_params
      flash[:success] = t ".update_success"
      redirect_to reports_url
    else
      flash[:danger] = t ".update_fail"
      render :edit
    end
  end

  def destroy
    if @report.destroy
      flash[:success] = t ".delete_success"
    else
      flash[:danger] = t ".delete_fail"
    end
    redirect_to reports_url
  end


  private

  def report_params
    params.require(:report).permit :title, :content
  end

  def load_report
    @report = current_user.reports.find_by id: params[:id]
    return if  @report
    flash[:danger] = t ".report_not_exist"
    redirect_to root_url
  end

  def correct_user
    @user = User.find_by id: @report.user_id
    return if current_user == @user
    flash[:danger] = t ".not_correct_user"
    redirect_to root_url
  end
end

app/views/reports/_report.html.erb
<tr>
  <td></td>
  <td>
    <p class="text-primary"><%= report.title %></p>
  </td>
  <td>
    <%= report.content %>
  </td>
  <td>
    <%= (report.updated_at).strftime t("time.formats.long") %>
  </td>
  <td>
    <%= link_to edit_report_path(report),
    class: "btn btn-primary btn-link btn-sm", rel: "tooltip", title: t(".edit") do %>
      <i class="material-icons">edit</i>
    <% end %>
    <%= link_to report_path(report), method: :delete,
    data: {confirm: t(".confirm")}, class: "btn btn-danger btn-link btn-sm", rel: "tooltip", title: t(".delete") do %>
      <i class="material-icons">close</i>
    <% end %>
  </td>
</tr>

app/views/reports/_report_form.html.erb
<%= form_for @report do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :content %>
        <%= f.text_area :content, rows: 5, class: "form-control" %>
      </div>
    </div>
  </div>
  <%= f.submit t(".report"), class: "btn btn-primary pull-right" %>
  <div class="clearfix"></div>
<% end %>

app/views/reports/edit.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title"><%= t ".edit_report" %></h4>
          </div>
          <div class="card-body">
            <%= render "report_form" %>
          </div>
        </div>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
</div>

app/views/reports/index.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-8">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title"><%= t ".add_a_report" %></h4>
          </div>
          <div class="card-body">
            <%= render "report_form" %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <%= search_form_for @q, url: reports_path, class: "navbar-form w-40 pull-right" do |f| %>
          <div class="input-group no-border">
            <%= f.search_field :title_cont, class: "form-control border", placeholder: t(".search") %>
            <%= select_tag :limit, options_from_collection_for_select(Settings.show_limit, :second, :second,
            selected: params[:limit] || Settings.show_limit.limit), class: "selectpicker", id: "show-limit" %>
            <%= f.submit class: "btn btn-primary btn-sm" %>
          </div>
        <% end %>
        <div class="card">
          <div class="card-header card-header-success">
            <h4 class="card-title "><%= t ".your_reports" %></h4>
          </div>
          <div class="card-body">
            <div class="table-responsive">
              <table class="table table-hover">
                <thead class=" text-primary">
                <th>#</th>
                <th>
                  <%= sort_link(@q, :title) do %>
                    <%= t ".title" %>
                  <% end %>
                </th>
                <th>
                  <%= sort_link(@q, :content) do %>
                    <%= t ".content" %>
                  <% end %>
                </th>
                <th>
                  <%= sort_link(@q, :created_at) do %>
                    <%= t ".updated_at" %>
                  <% end %>
                </th>
                <th>#</th>
                </thead>
                <tbody>
                  <%= render @reports %>
                </tbody>
              </table>
              <%= paginate @reports %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/reports/new.html.erb
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-2"></div>
      <div class="col-md-8">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title"><%= t ".add_a_report" %></h4>
          </div>
          <div class="card-body">
            <%= render "report_form" %>
          </div>
        </div>
      </div>
      <div class="col-md-2"></div>
    </div>
  </div>
</div>